# python3_install.yml
- name: Install IUM Repo
  become: yes
  yum: name={{ item }} state=latest
  ignore_errors: true
  with_items:
    - https://centos7.iuscommunity.org/ius-release.rpm

- name: Install Python 3.6 via IUM
  become: yes
  yum: name={{ item }} state=latest
  ignore_errors: true
  with_items:
    - python36u

- name: Install Python 2.7.13
  become: yes
  script: files/python2_7_13_install.sh

- name: Install pip for Python
  become: yes
  script: files/pip_install.sh

- name: Install virtualenv
  become: yes
  pip:
    name: virtualenv
